'Featured Rulebooks':
  - settlers-of-catan
  - everyone-is-john
  - monopoly
  - the-resistance
  
'Recently Added':
  - incan-gold
  - lord-of-the-rings-the-confrontation
  - lost-cities
  - san-juan
  - 7-wonders
  - spyfall
  - lords-of-waterdeep
  - ticket-to-ride
  - splendor
