'Featured Rulebooks':
  - settlers-of-catan
  - everyone-is-john
  - monopoly
  - the-resistance
  
'Recently Added':
  - spyfall
  - lords-of-waterdeep
  - ticket-to-ride
  - splendor
  - mille-bornes
