'Featured Rulebooks':
  - settlers-of-catan
  - everyone-is-john
  - monopoly
  - the-resistance
  
'Recently Added':
  - guillotine
  - drakon
  - incan-gold
  - lord-of-the-rings-the-confrontation
  - lost-cities
  - san-juan
  - 7-wonders
