'Featured Rulebooks':
  - settlers-of-catan
  - everyone-is-john
  - monopoly
  - the-resistance
  
'Recently Added':
  - puerto-rico
  - blood-rage
  - scythe
  - jamaica
  - jambo
  - guillotine
  - drakon
  - incan-gold
